# Generated by Django 5.0.1 on 2024-12-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], max_length=20, null=True)),
                ('antecedentes_medicos', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('talla', models.IntegerField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('saturacion', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
