# Generated by Django 5.0.1 on 2024-12-26 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12.345.678-K.', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')]),
        ),
    ]
