# Generated by Django 5.0.1 on 2024-12-26 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_paciente_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='usuarios.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='resultado',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
